{{- if .Values.backend.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-backend-data
  labels:
    {{- include "scuba-divelog.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.backend.persistence.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.backend.persistence.size }}
{{- end }}
