{{- if .Values.mysql.enabled }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  labels:
    app.kubernetes.io/instance: scuba
  name: scuba-app-db
  namespace: {{ .Release.Namespace }}
spec:
  encryptedData:
    DATABASE_URL: AgASLZARC+GJbzJqFj3HBteZndBvYVFOEwkLwtO2jt/Q7/1qEspTDyMwiRaFW1j0YUwIt1gsoloIn6Kqk9oCqIiCIXdo0r2rPxG/MHgT28z4tW9LA5Mc8KfOK0et8TZijtMWq3Zx0H2cNCFnPmB05g6St3f1LEFnvko3UPtP2U1UrMfY3rUf7Bxo6Evv4u3XBmF+oihSzngRAVzKDiv0bAZSVMjqWP2hm0up2e9S2XCT6lSJNRpWhE68G/a0LJ6pJpboeTKiSLBaXdtgLiNvOO/DkOXRs0TZL/rf5guZo6xeaJA/pa5nUtRhUnELHcYLE8Csg06LqGv6rkZKBPjPZnXZhSemmGcwvPn4iWN60C0VRq2rX0jCtVpML7exx+naN/z+HRCoWl69/YwkBodmIpup7FwEisErdk9XSjFhsqDt11Omp8DStH9S4J4xMs8vBncEpwEsKSpV5YKyZxoi5N69YFkpPlq2xTnEtt0r/hy2av2Yj8hDI1Xv7loyW9L+TFdS8r44mjYs2/mLX8vpsjfnzJX/yD2G2tRX9gtGNMgNbT0j5LB4vWwrs7tN0OUsYFv9OmpxWM+471YWiGy6l4AFqqfR7P0jKUWnTH1+56RIZpM9OayLZh00Vcrf/TVDPnzDqlqjzjRI/TbLPNkibd8r4C7pUIZNkwRAdbFlQgbapXM7tFMhAMYJ7uGNOzH4y0/vb0TA9W+PX9fhxf4cy0mEfSdn/jEFGBf7bfTGHUQZVF0GHT1/TA1Tq6IwREI8mfJVhri5cJoVHg==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      labels:
        app.kubernetes.io/instance: scuba
      name: scuba-app-db
      namespace: {{ .Release.Namespace }}
{{- end }}
