{{- if .Values.mysql.enabled }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  labels:
    app.kubernetes.io/instance: scuba
  name: scuba-app-db
  namespace: {{ .Release.Namespace }}
spec:
  encryptedData:
    DATABASE_URL: AgAOBPmEhBwBsKipJDetpsDQ79Klb4l4mDrB1KPhVsbF1+4oq+IHVOFvzydyV5obaRV4HeWDdpcp7ZKGf4A1Evz5oOHTFFh6sF2ahwhRfQK7I95bZlgqlEoqmoLDs7qsO5soRK9hLIyuwDyiUBYfnGnvnRzS9QcraZmmXSziO4vADfVBE95kBOWJeQ2BdZEHnniyDZvpxsXxSQ7b4F4uqlRe+uLxOLuQLk4vqMBf8yaNof0tWf+Q+UNuOAXOU9vZsEqwtAnG4HGcGDDsXIw8X48XInR3/5s7RORNUs7Y0qQuO6s4gEFExot4HSbWiUpfNIIy9P3oFoQJvYtatZvC2Ty0KAA3mmPpsCGjGY+YozIsP72Ncn8Zy/tbRePURvf3jJfrDzkRV3CI9jF/B62ih9VXA6iYNClLAMdaz6uXo67K7Ps054LDdnWoPZqtErzPyd3vwupPIjkLcNSQQEpynnLESNJvE1KkP/Fst7pT3o78iSoLYz61oyynBeD6S2k/5sEIKkNUYo6CW2SWXZTYF/sVceJ2cF0lkbas23FovZ7tGu13PUoXfvgK4MD4aK2iK7fe9Q78712xcUut09OLJ80L4TXBegaWg7g8B2SOmu6FwAIMJT4A3OskchfgxQEVjwuV3jwxbtFPg+ULOxjD58Cx6SpF1JpOZ/rZYXz1RqAyEKB4Kx3B6fix2nTeWNG3DPMuxfNttSkYOaVCsHhOlPRIoZk6BzbxAIqLGxOlOAm2UL4++TSOXqxJB995Erj8QS3ORYZ2CbHJ6bBDQ4rkYKyOau0FEE7JAxoKi471aVMh
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      labels:
        app.kubernetes.io/instance: scuba
      name: scuba-app-db
      namespace: {{ .Release.Namespace }}
{{- end }}
